openapi: 3.0.1
info:
  title: Agentforce Action
  description: Basic example of an Agentforce Action
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Agentforce Action
  description: Basic Agentforce Action example
paths:
  /generateBadge:
    post:
      tags:
      - Agentforce Action
      operationId: generateBadge
      description: Use this action in response to requests for a Heroku badge with a name on it.
      parameters:
      - name: name
        in: query
        required: true
        description: Name to be placed on the badge.
        schema:
          type: string
      responses:
        "200":
          description: This is the Heroku badge the user requested.
          content:
            '*/*':
              schema:
                type: string
      x-sfdc:
        heroku:
          authorization:
            connectedApp: BadgeServiceConnectedApp
            permissionSet: BadgeServicePermissions
components: {}
